export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_CURRENT_SONG_INDEX = 'SET_CURRENT_SONG_INDEX'

export const SET_CURRENT_TIME_AUTO = 'SET_CURRENT_TIME_AUTO'

export const SET_VOLUME = 'SET_VOLUME'
